goal_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i(new create)
  resources :goals
  resource :session, only: %i(new create destroy) 
end

goal_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goal_app/app/models/goal.rb
class Goal < ApplicationRecord
  validates :user_id, :body, :title, presence: true

  belongs_to :user

  before_save :default_values
  def default_values
    if hidden.nil?
      self.hidden = false
    else
      self.hidden = true
    end
  end
end

goal_app/app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :goals

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    save
    session_token
  end

  def password=(pass)
    @password = pass
    self.password_digest = BCrypt::Password.create(pass)
  end

  def is_password?(maybe)
    BCrypt::Password.new(password_digest).is_password?(maybe)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end
end

goal_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user 
    return nil unless session[:session_token]
    @user ||= User.find_by(session_token: session[:session_token])
  end


end

goal_app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
    render :new
  end

  def create
    # debugger
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  private
  def goal_params
    params.require(:goal).permit(:title, :body)
  end
end

goal_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      session[:session_token] = @user.session_token
      redirect_to goals_url
    else
      flash.now[:errors] = ["invalid params"]
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to goals_url
  end

end

goal_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:session_token] = @user.session_token
      redirect_to goals_url
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goal_app/app/helpers/application_helper.rb
module ApplicationHelper
end

goal_app/app/helpers/goals_helper.rb
module GoalsHelper
end

goal_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

goal_app/app/helpers/users_helper.rb
module UsersHelper
end

goal_app/app/views/goals/index.html.erb
<h1>homepage</h1>

goal_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <header>
    <% if !!current_user %>
      <%= current_user.username %>
      <%= button_to 'Log Out', session_url, method: :delete %>
    <% end  %>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

goal_app/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="username">Username
    <input type="text" name="user[username]" value="">
  </label>

  <label for="username">Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up">

</form>